In [1]:
import pandas as pd
import numpy as np
import os
import pickle
import networkx as nx
import mygene
import torch

In [2]:
current_directory = os.getcwd()

somepath = os.path.abspath(
    os.path.join(current_directory, '..', 'Data', 'RNA_dataset_tabular_R3.csv'))

# expression data
tabular_data = pd.read_csv(somepath, sep = ',', index_col = 0)
tabular_data

NFKB1  TNIP2  AMOT  VASP  SS18L1  SMARCA4  \
id                                                                             
X00936b9285d6b8665ae9122993fb8e91   6.10   4.38  3.07  6.14    4.70     7.52   
X105622fadc33f23755ac2df823110aca   5.07   3.33  1.73  5.11    5.62     6.58   
Xe44f39747a8e84b02b4cb24659312144   6.13   4.41  3.23  6.32    5.57     8.02   
X293dd1284496215e9a0eca9f17a98e7e   5.82   4.30  3.44  6.45    4.86     7.45   
X01ed7190ce00862696edbf047b542045   6.15   4.21  3.90  5.93    4.43     7.60   
...                                  ...    ...   ...   ...     ...      ...   
X50772aa64efb859960b20f8801cd6f58   6.27   3.78  3.98  5.95    4.66     7.18   
X91bcd3067a1a7954692d836515e04869   6.12   3.94  3.25  6.09    4.98     7.32   
Xc7439a06ffa32b313b0ec1b987b992a2   5.91   3.62  3.34  5.80    8.86     8.69   
X21a6043653d187f8bbead475d2f49791   6.48   4.32  2.27  6.10    5.13     7.83   
Xa021f5de25a2ffa059870f059a65d075   5.76   4.79  3.19  6.37    4.51     8.03   

                                   SMURF1  HSPA5  SKIL  UBE2I  ...  SLC17A1  \
id                                                             ...            
X00936b9285d6b8665ae9122993fb8e91    4.93   8.37  6.21   5.69  ...     4.47   
X105622fadc33f23755ac2df823110aca    4.34   7.42  6.15   4.86  ...     4.45   
Xe44f39747a8e84b02b4cb24659312144    5.14   7.55  6.87   6.27  ...     2.94   
X293dd1284496215e9a0eca9f17a98e7e    4.90   8.39  6.83   5.70  ...     0.83   
X01ed7190ce00862696edbf047b542045    4.74   8.31  6.38   5.94  ...     6.70   
...                                   ...    ...   ...    ...  ...      ...   
X50772aa64efb859960b20f8801cd6f58    4.61   8.04  6.62   5.80  ...     7.81   
X91bcd3067a1a7954692d836515e04869    5.02   8.21  6.71   5.89  ...     0.01   
Xc7439a06ffa32b313b0ec1b987b992a2    4.52   8.15  5.77   6.85  ...     7.31   
X21a6043653d187f8bbead475d2f49791    5.18   8.34  6.70   6.02  ...     9.17   
Xa021f5de25a2ffa059870f059a65d075    4.86   8.26  5.37   5.89  ...     5.90   

                                   MGST2  CHPT1  STK17A  SULF2  CD276  TIPARP  \
id                                                                              
X00936b9285d6b8665ae9122993fb8e91   7.07   5.23    4.08   8.68   7.09    4.94   
X105622fadc33f23755ac2df823110aca   7.40   6.84    2.84   6.08   6.56    4.61   
Xe44f39747a8e84b02b4cb24659312144   6.66   5.81    4.16   6.33   7.14    8.42   
X293dd1284496215e9a0eca9f17a98e7e   6.67   5.27    4.12   6.97   6.73    6.28   
X01ed7190ce00862696edbf047b542045   6.53   5.84    4.35   5.67   6.66    4.93   
...                                  ...    ...     ...    ...    ...     ...   
X50772aa64efb859960b20f8801cd6f58   7.26   6.15    3.52   5.92   6.74    5.48   
X91bcd3067a1a7954692d836515e04869   6.38   5.20    4.05   7.84   7.59    7.59   
Xc7439a06ffa32b313b0ec1b987b992a2   6.76   7.12    3.25   6.81   6.82    5.27   
X21a6043653d187f8bbead475d2f49791   7.04   5.46    4.10   6.70   7.98    5.24   
Xa021f5de25a2ffa059870f059a65d075   6.24   5.74    3.18   7.41   7.33    8.22   

                                   WNT16        PFS  CENSOR  
id                                                           
X00936b9285d6b8665ae9122993fb8e91   0.01   4.172485     0.0  
X105622fadc33f23755ac2df823110aca   0.01  16.591376     1.0  
Xe44f39747a8e84b02b4cb24659312144   0.01  11.104723     0.0  
X293dd1284496215e9a0eca9f17a98e7e   0.01  14.028747     1.0  
X01ed7190ce00862696edbf047b542045   0.01  12.418891     0.0  
...                                  ...        ...     ...  
X50772aa64efb859960b20f8801cd6f58   0.01   4.271047     0.0  
X91bcd3067a1a7954692d836515e04869   0.01   2.496920     0.0  
Xc7439a06ffa32b313b0ec1b987b992a2   0.01   6.505133     1.0  
X21a6043653d187f8bbead475d2f49791   0.01   5.683778     1.0  
Xa021f5de25a2ffa059870f059a65d075   0.01   4.106776     1.0  

[726 rows x 3111 columns]

In [7]:
print(set(tabular_data.dtypes))

{dtype('float64')}


In [32]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

scaler = MinMaxScaler()

X = tabular_data.drop(columns=['PFS'])
Y = tabular_data['PFS']
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 42)

X_train = pd.DataFrame(scaler.fit_transform(X_train), columns = X_train.columns, index = X_train.index)
X_test = pd.DataFrame(scaler.fit_transform(X_test), columns = X_test.columns, index = X_test.index)

Y_train

id
Xf7ee4a331a8fd70edc240dff978c170d    13.897331
X5cabb9f0afcc6ec89f28a72e66b75c5b     3.909651
X2069a43cf26725e339dae5a64490a17f     1.379877
X3cdb45cfe9ffaac83f36c75e4af759e6     3.745380
X8783adc097e910b52c11f50e2a4aff2a     9.626283
                                       ...    
Xe1b0f87c25889df31bc0fe76a68853b6    12.517454
X502dfff1180e1952d964196c8493633b     0.032854
Xfdb742505b30978af60b426c93a32f9e     5.585216
X5db2ba740f908fe3a3e6832d48949346     1.412731
X490b3aaf0b34d71712e894ca670bff00     7.030801
Name: PFS, Length: 580, dtype: float64

In [34]:
torch.tensor(Y_train.values)

tensor([13.8973,  3.9097,  1.3799,  3.7454,  9.6263, 19.3511,  6.8994,  8.5749,
         1.6099,  6.9651,  5.6509,  4.2382,  2.5626,  8.4107,  1.2485,  1.4127,
         7.1622,  4.2053,  6.9322,  8.3121,  7.0308,  8.3450,  8.3450,  6.9322,
        12.3203,  1.4127,  0.4928,  1.4127, 11.3018,  2.8583,  1.4127,  8.2464,
         4.1725,  6.9322,  0.0329,  4.1725,  6.8994,  8.1150, 13.8316, 18.0041,
        16.6571,  2.8583,  4.1725,  1.4127,  4.4353,  5.4209, 10.8419,  2.7926,
         1.4127,  3.0226,  5.8480,  6.7680, 11.0719,  8.0493,  2.9240,  2.6283,
        14.0616, 12.6160,  2.7926, 12.2546,  5.5524,  4.2053,  6.9322,  6.9322,
         8.3121,  8.3121,  5.6181, 12.5832,  4.8296,  4.1396,  9.9220,  4.1068,
         8.3778, 11.1704,  4.1725,  8.3121,  1.4456,  5.6181, 20.7967,  3.2526,
        13.8645,  1.5113,  1.4456,  9.6591,  9.6920,  9.7577, 12.4517, 15.3101,
         9.6920,  5.7823,  7.7207,  7.0965,  9.5934, 23.6222,  2.7926,  1.5770,
         5.5524,  1.3799,  2.8583, 11.17

In [30]:
dataobj = X_train.iloc[0]
dataobj = torch.tensor(dataobj.values)
dataobj.reshape(-1, len(dataobj))

tensor([[0.6465, 0.4970, 0.4626,  ..., 0.4338, 0.3231, 0.0000]],
       dtype=torch.float64)

In [7]:
current_directory = os.getcwd()

somepath = os.path.abspath(
    os.path.join(current_directory, '..', 'Data', 'RNA_dataset_graph_R3.pkl'))

with open(somepath, 'rb') as f:
    loaded_object = pickle.load(f)

In [8]:
loaded_object

In [38]:
x = [[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6]]]
x

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
 [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
 [[1, 2, 3], [4, 5, 6]]]

In [42]:
[j for i in x for j in i]

[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9],
 [1, 2, 3],
 [4, 5, 6],
 [7, 8, 9],
 [1, 2, 3],
 [4, 5, 6]]

In [44]:
from sksurv.datasets import load_breast_cancer
from sksurv.linear_model import CoxPHSurvivalAnalysis, CoxnetSurvivalAnalysis
from sksurv.preprocessing import OneHotEncoder

X, y = load_breast_cancer()
y

array([( True,  723.), (False, 6591.), ( True,  524.), (False, 6255.),
       ( True, 3822.), (False, 6507.), (False, 5947.), (False, 5816.),
       (False, 6007.), ( True, 1233.), ( True, 1136.), (False, 5984.),
       (False, 6249.), ( True, 4066.), ( True,  690.), ( True,  994.),
       ( True,  434.), ( True, 1743.), ( True, 2863.), (False, 5693.),
       (False, 5823.), (False, 5785.), (False, 5661.), (False, 2909.),
       ( True, 1171.), (False, 5110.), (False, 5533.), (False, 5571.),
       (False, 5519.), (False, 5379.), (False, 4675.), (False, 4652.),
       (False, 4227.), ( True,  910.), (False, 4472.), ( True, 1206.),
       (False, 7057.), (False,  958.), (False, 5359.), (False, 5945.),
       (False, 5651.), ( True,  528.), ( True,  796.), (False, 5685.),
       ( True, 1023.), (False, 4791.), (False, 1215.), (False, 3779.),
       (False, 5306.), (False, 5678.), ( True,  421.), (False, 5612.),
       ( True, 3121.), (False, 1104.), (False, 4691.), (False, 5238.),
      

In [8]:
import matplotlib.pyplot as plt

In [14]:
start = 0.0001
stop = 0.1
step = 0.0001

# Generate the linearly spaced numbers
linear_numbers = np.arange(start, stop + step, step)
linear_numbers

array([0.0001, 0.0002, 0.0003, 0.0004, 0.0005, 0.0006, 0.0007, 0.0008,
       0.0009, 0.001 , 0.0011, 0.0012, 0.0013, 0.0014, 0.0015, 0.0016,
       0.0017, 0.0018, 0.0019, 0.002 , 0.0021, 0.0022, 0.0023, 0.0024,
       0.0025, 0.0026, 0.0027, 0.0028, 0.0029, 0.003 , 0.0031, 0.0032,
       0.0033, 0.0034, 0.0035, 0.0036, 0.0037, 0.0038, 0.0039, 0.004 ,
       0.0041, 0.0042, 0.0043, 0.0044, 0.0045, 0.0046, 0.0047, 0.0048,
       0.0049, 0.005 , 0.0051, 0.0052, 0.0053, 0.0054, 0.0055, 0.0056,
       0.0057, 0.0058, 0.0059, 0.006 , 0.0061, 0.0062, 0.0063, 0.0064,
       0.0065, 0.0066, 0.0067, 0.0068, 0.0069, 0.007 , 0.0071, 0.0072,
       0.0073, 0.0074, 0.0075, 0.0076, 0.0077, 0.0078, 0.0079, 0.008 ,
       0.0081, 0.0082, 0.0083, 0.0084, 0.0085, 0.0086, 0.0087, 0.0088,
       0.0089, 0.009 , 0.0091, 0.0092, 0.0093, 0.0094, 0.0095, 0.0096,
       0.0097, 0.0098, 0.0099, 0.01  , 0.0101, 0.0102, 0.0103, 0.0104,
       0.0105, 0.0106, 0.0107, 0.0108, 0.0109, 0.011 , 0.0111, 0.0112,
      